version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: myapp_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet

  backend:
    image: hardik478/notes-backend:latest
    build: ./notes-backend
    container_name: myapp_backend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://root:example@mongo:27017/notesdb?authSource=admin
    networks:
      - appnet
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    image: hardik478/notes-frontend:latest
    build: ./notes-frontend
    container_name: myapp_frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - appnet
    depends_on:
      - backend

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: myapp_reverseproxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet
    depends_on:
      - frontend
      - backend

networks:
  appnet:
    driver: bridge

volumes:
  mongo_data:
